#!/bin/bash
set -euo pipefail

# HavenClaw Local Installer
# Install HavenClaw from local repository for development
# Deployed on Avalanche Fuji Testnet
#
# Usage: bash scripts/install-local.sh
#
# Installer akan MEMINTA semua konfigurasi secara interactive!

BOLD='\033[1m'
SUCCESS='\033[38;2;0;229;204m'
INFO='\033[38;2;136;146;176m'
WARN='\033[38;2;255;176;32m'
ERROR='\033[38;2;230;57;70m'
NC='\033[0m'

echo -e "${BOLD}🏛️ HavenClaw Local Installer${NC}"
echo -e "${INFO}Deployed on Avalanche Fuji Testnet${NC}"
echo -e "${INFO}Installing from local repository for development${NC}"
echo ""

# Show Next Steps at the BEGINNING
echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${INFO}  What Will Happen${NC}"
echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "This installer will:"
echo "  1. Build HavenClaw from source"
echo "  2. Ask for your private key (encrypted storage)"
echo "  3. Configure Fuji Testnet automatically"
echo "  4. Ask for agent name & capabilities"
echo "  5. Optionally register your agent on Fuji"
echo ""
echo -e "${WARN}⚠️  Before You Start:${NC}"
echo ""
echo "  1. Have your private key ready"
echo "     (0x + 64 hex characters)"
echo ""
echo "  2. Get test AVAX from faucet:"
echo -e "     ${INFO}https://faucet.avax.network/${NC}"
echo "     (Required for agent registration)"
echo ""
echo "  3. Add to PATH after install:"
echo -e "     ${INFO}export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
echo ""
echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

read -p "Continue with installation? (y/N): " continue_input
if [[ ! "$continue_input" =~ ^[Yy]$ ]]; then
    echo -e "${INFO}Installation cancelled.${NC}"
    exit 0
fi

echo ""

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo -e "${INFO}Project root: ${PROJECT_ROOT}${NC}"
echo ""

# Check if we're in the right place
if [[ ! -f "$PROJECT_ROOT/package.json" ]]; then
    echo -e "${ERROR}✗ Error: package.json not found${NC}"
    echo -e "${ERROR}  Make sure you're running this from the havenclaw directory${NC}"
    exit 1
fi

# Check Node.js version
if command -v node &> /dev/null; then
    NODE_VERSION=$(node --version)
    NODE_MAJOR=$(echo $NODE_VERSION | cut -d'.' -f1 | sed 's/v//')
    if [[ $NODE_MAJOR -lt 22 ]]; then
        echo -e "${WARN}! Warning: Node.js $NODE_VERSION found, but 22+ recommended${NC}"
    else
        echo -e "${SUCCESS}✓ Node.js ready ($NODE_VERSION)${NC}"
    fi
else
    echo -e "${ERROR}✗ Node.js not found${NC}"
    echo "Please install Node.js 22+ from https://nodejs.org"
    exit 1
fi

# Check pnpm
if command -v pnpm &> /dev/null; then
    PNPM_VERSION=$(pnpm --version)
    echo -e "${SUCCESS}✓ pnpm ready ($PNPM_VERSION)${NC}"
else
    echo -e "${WARN}! pnpm not found, installing...${NC}"
    if command -v npm &> /dev/null; then
        npm install -g pnpm
        if command -v pnpm &> /dev/null; then
            echo -e "${SUCCESS}✓ pnpm installed${NC}"
        else
            echo -e "${ERROR}✗ Failed to install pnpm${NC}"
            exit 1
        fi
    else
        echo -e "${ERROR}✗ npm not found either${NC}"
        exit 1
    fi
fi

echo ""
echo -e "${BOLD}Installing dependencies...${NC}"
cd "$PROJECT_ROOT"
pnpm install

echo ""
echo -e "${BOLD}Building HavenClaw...${NC}"
pnpm build

echo ""
echo -e "${BOLD}Creating global wrapper script...${NC}"

# Create user local bin if it doesn't exist
mkdir -p "$HOME/.local/bin"

# Add to PATH if not already
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    echo -e "${WARN}! Adding $HOME/.local/bin to PATH${NC}"
    
    # Add to shell rc files
    for rc in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.bash_profile"; do
        if [[ -f "$rc" ]] && ! grep -q ".local/bin" "$rc"; then
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$rc"
            echo -e "${INFO}  Added to $rc${NC}"
        fi
    done
    
    echo -e "${WARN}  Please restart your shell or run: export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
fi

# Find the CLI entry file (could be .js or .mjs)
CLI_ENTRY=""
if [[ -f "$PROJECT_ROOT/dist/cli/entry.js" ]]; then
    CLI_ENTRY="entry.js"
elif [[ -f "$PROJECT_ROOT/dist/cli/entry.mjs" ]]; then
    CLI_ENTRY="entry.mjs"
else
    echo -e "${ERROR}✗ CLI entry file not found in dist/cli/${NC}"
    exit 1
fi

# Create wrapper script
cat > "$HOME/.local/bin/havenclaw" << EOF
#!/bin/bash
# HavenClaw CLI Wrapper
# Generated by install-local.sh

NODE_PATH="$PROJECT_ROOT/dist/cli/$CLI_ENTRY"

if [ ! -f "\$NODE_PATH" ]; then
    echo "Error: HavenClaw CLI not found at \$NODE_PATH"
    echo "Please run: cd $PROJECT_ROOT && pnpm build"
    exit 1
fi

exec node "\$NODE_PATH" "\$@"
EOF

chmod +x "$HOME/.local/bin/havenclaw"

echo -e "${SUCCESS}✓ Wrapper created: $HOME/.local/bin/havenclaw${NC}"

# Create config directory
mkdir -p "$HOME/.havenclaw"
echo -e "${SUCCESS}✓ Config directory created: $HOME/.havenclaw${NC}"

# Interactive Configuration Setup
echo ""
echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${INFO}  Configuration Setup${NC}"
echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BOLD}Please enter your configuration:${NC}"
echo ""

# Ask for private key
echo -e "${WARN}⚠️  Wallet Configuration${NC}"
echo "   Your private key will be encrypted and stored securely."
echo "   Used for signing transactions on Fuji Testnet."
echo ""
read -s -p "Enter your private key (0x + 64 hex chars): " HAVENCLAW_PRIVATE_KEY
echo ""

if [[ -n "$HAVENCLAW_PRIVATE_KEY" ]]; then
    if [[ "$HAVENCLAW_PRIVATE_KEY" =~ ^0x[a-fA-F0-9]{64}$ ]]; then
        # Store encrypted wallet
        echo "$HAVENCLAW_PRIVATE_KEY" | openssl enc -aes-256-cbc -pbkdf2 -iter 100000 -salt -out "$HOME/.havenclaw/.wallet.enc" -pass pass:"havenclaw_auto_$(date +%s)" 2>/dev/null || \
        echo "$HAVENCLAW_PRIVATE_KEY" | base64 > "$HOME/.havenclaw/.wallet"
        chmod 600 "$HOME/.havenclaw/.wallet.enc" 2>/dev/null || chmod 600 "$HOME/.havenclaw/.wallet"
        echo -e "${SUCCESS}✓ Wallet configured securely${NC}"
    else
        echo -e "${WARN}! Invalid private key format, skipping wallet storage${NC}"
        HAVENCLAW_PRIVATE_KEY=""
    fi
else
    echo -e "${WARN}! No private key entered, skipping wallet storage${NC}"
fi

echo ""
echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${INFO}  Network Configuration${NC}"
echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "   Using Avalanche Fuji Testnet (recommended for development)"
HAVENCLAW_NETWORK="fuji"
echo -e "${SUCCESS}✓ Network: $HAVENCLAW_NETWORK${NC}"

# RPC URL for Fuji
HAVENCLAW_RPC_URL="https://api.avax-test.network/ext/bc/C/rpc"
echo -e "${SUCCESS}✓ RPC: Fuji Testnet${NC}"

echo ""
echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${INFO}  Agent Configuration${NC}"
echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
read -p "Enter agent name [My AI Agent]: " HAVENCLAW_AGENT_NAME_INPUT
HAVENCLAW_AGENT_NAME="${HAVENCLAW_AGENT_NAME_INPUT:-My AI Agent}"

read -p "Enter capabilities (comma-separated, e.g., trading,analysis): " HAVENCLAW_CAPABILITIES
echo ""

# Ask about auto-register on Fuji
echo -e "${BOLD}Agent Registration on Fuji Testnet:${NC}"
echo "  Would you like to register your agent on Fuji Testnet now?"
echo "  (Requires test AVAX tokens from faucet)"
echo "  Faucet: https://faucet.avax.network/"
read -p "Register agent? (y/N): " AUTO_REGISTER_INPUT
if [[ "$AUTO_REGISTER_INPUT" =~ ^[Yy]$ ]]; then
    AUTO_REGISTER="1"
else
    AUTO_REGISTER="0"
fi

# Create config file (ALWAYS - with Fuji configuration)
cat > "$HOME/.havenclaw/config.json" << EOF
{
  "network": "fuji",
  "agentName": "${HAVENCLAW_AGENT_NAME:-My AI Agent}",
  "installDaemon": false,
  "rpcUrl": "https://api.avax-test.network/ext/bc/C/rpc",
  "chainId": 43113,
  "preferences": {
    "autoApprove": false,
    "notifications": true
  }
}
EOF
echo -e "${SUCCESS}✓ Configuration created: $HOME/.havenclaw/config.json${NC}"

# Auto-register agent if configured
if [[ "$AUTO_REGISTER" == "1" && -n "$HAVENCLAW_PRIVATE_KEY" && -n "$HAVENCLAW_AGENT_NAME" ]]; then
    echo ""
    echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${INFO}  Auto-Registering Agent on Fuji...${NC}"
    echo -e "${INFO}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "Agent Name: ${HAVENCLAW_AGENT_NAME}"
    [[ -n "$HAVENCLAW_CAPABILITIES" ]] && echo -e "Capabilities: ${HAVENCLAW_CAPABILITIES}"
    echo -e "Network: Fuji Testnet"
    echo ""
    
    # Set private key as environment variable for the CLI
    export HAVENCLAW_PRIVATE_KEY="$HAVENCLAW_PRIVATE_KEY"
    export HAVENCLAW_RPC_URL="https://api.avax-test.network/ext/bc/C/rpc"
    
    if [[ -n "$HAVENCLAW_CAPABILITIES" ]]; then
        "$HOME/.local/bin/havenclaw" agent register --name "$HAVENCLAW_AGENT_NAME" --capabilities "$HAVENCLAW_CAPABILITIES" || \
        echo -e "${WARN}! Agent registration failed. You can register manually later with:${NC}"
        echo -e "${INFO}  havenclaw agent register --name \"${HAVENCLAW_AGENT_NAME}\" --capabilities ${HAVENCLAW_CAPABILITIES}${NC}"
    else
        "$HOME/.local/bin/havenclaw" agent register --name "$HAVENCLAW_AGENT_NAME" || \
        echo -e "${WARN}! Agent registration failed. You can register manually later with:${NC}"
        echo -e "${INFO}  havenclaw agent register --name \"${HAVENCLAW_AGENT_NAME}\"${NC}"
    fi
    
    # Clear private key from environment
    unset HAVENCLAW_PRIVATE_KEY
fi

echo ""
echo -e "${SUCCESS}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${SUCCESS}✓ HavenClaw installed successfully!${NC}"
echo -e "${SUCCESS}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BOLD}Configuration Summary:${NC}"
echo -e "  Network: ${SUCCESS}Fuji Testnet${NC}"
echo -e "  Chain ID: 43113"
echo -e "  Config:  $HOME/.havenclaw/config.json"
echo -e "  RPC:     https://api.avax-test.network/ext/bc/C/rpc"
if [[ -f "$HOME/.havenclaw/.wallet" ]] || [[ -f "$HOME/.havenclaw/.wallet.enc" ]]; then
    echo -e "  Wallet:  ${SUCCESS}Configured${NC}"
else
    echo -e "  Wallet:  ${WARN}Not configured${NC}"
fi
if [[ "$AUTO_REGISTER" == "1" && -n "$HAVENCLAW_AGENT_NAME" ]]; then
    echo -e "  Agent:   ${SUCCESS}$HAVENCLAW_AGENT_NAME${NC}"
fi
echo ""
echo -e "${BOLD}Next Steps:${NC}"
echo ""
echo "  1. Add to PATH (if not already done):"
echo -e "     ${INFO}export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
echo ""
echo "  2. Get test AVAX from faucet:"
echo -e "     ${INFO}https://faucet.avax.network/${NC}"
echo ""
echo "  3. Verify installation:"
echo -e "     ${INFO}havenclaw --version${NC}"
echo ""
echo "  4. Check wallet balance:"
echo -e "     ${INFO}havenclaw wallet balance${NC}"
echo ""
echo "  5. Register agent (if not auto-registered):"
echo -e "     ${INFO}havenclaw agent register --name \"My Bot\" --capabilities trading,analysis${NC}"
echo ""
echo -e "${INFO}For development, you can also run:${NC}"
echo -e "     ${INFO}cd $PROJECT_ROOT && node dist/cli/$CLI_ENTRY${NC}"
echo ""
echo -e "${INFO}Documentation: https://docs.havenclaw.ai${NC}"
echo -e "${INFO}Fuji Explorer: https://testnet.snowtrace.io${NC}"
echo ""
